apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: vpc.block.csi.ibm.io
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: false
  seLinuxMount: true
  volumeLifecycleModes:
    - Persistent
